[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npx prisma migrate deploy && npm start"
healthcheckPort = 3000
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
