[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "npx prisma migrate deploy && node node_modules/.bin/next start -H 0.0.0.0 -p 3000"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
